[package]
name = "hash-to-curve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
lazy_static = "1.4.0"
libcrux = { git = "https://github.com/cryspen/libcrux" }
num-bigint = "0.4.3"
num-traits = "0.2.15"

[dev-dependencies]
serde_json = "1.0.102"
