[workspace]
members = [
    "scrambledb",
    "elgamal",
    "hash-to-curve",
    "p256",
    "oprf",
    "hacspec_lib",
    "prp",
    "sha256",
    "hmac"
]

[workspace.dependencies]
libcrux = { git = "https://github.com/cryspen/libcrux" }
hacspec_lib = { path = "./hacspec_lib" }
