name: Build and Deploy GH Pages for ATLAS

on:
    workflow_dispatch:
    push:
        branches:
            - main

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    working-directory: hacspec-scrambledb
    

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    docs:
        environment:
              name: github-pages
              url: ${{ steps.deployment.outputs.page_url }}
              
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build Documentation
              run: |
                cargo doc --no-deps
                echo "<meta http-equiv=\"refresh\" content=\"0; url=scrambledb\">" > target/doc/index.html
                cp -r target/doc docs

            - name: Upload Documentation Artifact
              uses: actions/upload-pages-artifact@v2
              with:
                path: "hacspec-scrambledb/docs"

            - name: Deploy Documentation to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
