name: Build and test ScrambleDB

on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: hacspec-scrambledb
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
            os:
                - macos-latest
                - ubuntu-latest
                - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Check formatting
      run: cargo fmt --all --check

    - name: Build Documentation
      run: |
        cargo doc --no-deps
        echo "<meta http-equiv=\"refresh\" content=\"0; url=scrambledb\">" > target/doc/index.html
        cp -r target/doc docs

    - name: Upload Documentation Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "hacspec-scrambledb/docs"

    - name: Deploy Documentation to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

